Some code review fixes
WANdisco/ansible-modules pull request #2
Opened 2021-03-12 11:24 UTC by nikitamishustin

2021-03-12 15:15 UTC, dchernykh79 requested changes

2021-03-15 09:02 UTC, nikitamishustin commented on cloudera_cm_config.py
>      cm_config = CM(name=params["cm_host"], api_client=api_client)
Then we can just try-except all requests to the API.

2021-03-15 09:19 UTC, nikitamishustin commented on cloudera_cm_config.py
> +        if 'parcel' in new_prop.lower():
> This API could be used following two scenarios.
> - User updated Cloudera Manager's local parcel repository.
> - User updated remote parcel locations.

So I think we can use something like this:
```
if new_prop.lower() in ('parcel_repo_path', 'remote_parcel_repo_urls'):
```

2021-03-15 09:25 UTC, nikitamishustin commented on cloudera_cm_config.py
> +        if 'parcel' in new_prop.lower():
If `new_prop` is not about parcels - we can use a global refresh method: https://archive.cloudera.com/cm7/7.2.4/generic/jar/cm_api/swagger-html-sdk-docs/python/docs/ClustersResourceApi.html#refresh

2021-03-17 12:56 UTC, Lozmanov commented on cloudera_parcel.py
> +    def _deacrivate(self):
deactivate

2021-03-17 13:06 UTC, nikitamishustin commented on cloudera_parcel.py
> +    def _deacrivate(self):
fixed

2021-03-17 13:06 UTC, nikitamishustin commented on cloudera_parcel.py
> +        self.parcel_api_client_instance.activate_command(self.cluster_name, self.name, self.version)
fixed

2021-03-24 08:34 UTC, merged